### ISSUE TITLE
Create a clear layer of persistence

### ISSUE THREAD

**Issue by marcelinol** [Bizcoito/trakinas#5]
We are using the FirebaseManager directly, but it is better to have a `BookRepository` class where we could use any kind of adapter to write and read data from the current database technology we want.

This will make the migration from firebase to any other database easier.

Wdyt @LeoSL ?

**Comment by LeoSL** [comment]
Mksnc :+1:

**Comment by marcelinol** [comment]
![image](https://user-images.githubusercontent.com/7313714/34366675-6c127804-ea86-11e7-8ad3-1d8fa60c5edc.png)
![image](https://user-images.githubusercontent.com/7313714/34366681-822ba886-ea86-11e7-88c2-6b84df915985.png)

**Comment by marcelinol** [comment]
Here's a sketch:

```
BooksRepository
- getBooks()
- getBook(id)
- createBook()
- updateBook({})
- searchBook()
```

I'm not sure about how the last one should work, but let's get our hands dirty :raised_hands:
